name: ci
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'refactor/**'
      - 'chore/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    name: 리액트 프로젝트 빌드
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v2
      
      - name: 노드 버전 체크
        run: node -v
      
      - name: 패키지 설치
        run: npm install

      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      
      - name: 패키지 빌드 
        run: npm run build

      - name: S3 업로드
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region ap-northeast-2 build s3://sgsg-deploy/frontend/build.zip